services:
  postgres:
    image: postgres:16
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: erp_db
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./sample_data:/sample_data:ro

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: Asia/Seoul
      TZ: Asia/Seoul
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_RESTRICT_FILE_ACCESS_TO: /files
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/files:rw
    depends_on:
      - postgres

volumes:
  n8n_data:
  pg_data: